### ISSUE TITLE
Asyncio Timeout error after command is complete

### ISSUE THREAD

**Issue by LeptoSpira** [LeptoSpira/offthedialbot#28]
> #### After completing a command, sometimes a Timeout Error will occur for no reason

## Traceback
```swift
Task exception was never retrieved
future: <Task finished coro=<wait_for() done, defined at /usr/local/lib/python3.7/asyncio/tasks.py:397> exception=TimeoutError()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 449, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
Task exception was never retrieved
future: <Task finished coro=<wait_for() done, defined at /usr/local/lib/python3.7/asyncio/tasks.py:397> exception=TimeoutError()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 449, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
Task exception was never retrieved
future: <Task finished coro=<wait_for() done, defined at /usr/local/lib/python3.7/asyncio/tasks.py:397> exception=TimeoutError()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 449, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
Task exception was never retrieved
future: <Task finished coro=<wait_for() done, defined at /usr/local/lib/python3.7/asyncio/tasks.py:397> exception=TimeoutError()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 449, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
```
*Note: This entire Traceback happens at once.*

**Comment by LeptoSpira** [comment]
One specific replicable situation:
- Completing `$profile create` and waiting 120 seconds

**Comment by LeptoSpira** [comment]
## Update to `Steps to reproduce` based on changes from #12
- Run command `$profile update cxp`
  - Complete the command (don't cancel it)
```swift
future: <Task finished name='ui.cancel' coro=<wait_for() done, defined at C:\Python\Python38-32\lib\asyncio\tasks.py:434> exception=TimeoutError()>
```
This is most likely because of this code:
> - https://github.com/LeptoSpira/offthedialbot/blob/master/offthedialbot/commands/profile/create.py#L97
> - https://github.com/LeptoSpira/offthedialbot/blob/master/offthedialbot/commands/profile/create.py#L154-L177
